### ISSUE TITLE
python 3.4 vs 3.5

### ISSUE THREAD

**Issue by mk-j** [freeseek/getmyancestors#14]
The code says:
```
sys.stderr.write('Python >= 3.4 is required to run this script\n')
```

yet python3.4 says:
```
  File "./getmyancestors.py", line 891
    async def download_tree(func, todo, n, loop):
            ^
SyntaxError: invalid syntax
```

I am running python 3.4....
Async def appears to be for python 3.5 only:

https://docs.python.org/3/reference/compound_stmts.html#coroutines

**Comment by mk-j** [comment]
Also, your readme says:
"Current version was updated on July 4th 2016."
Yet you have commits in 2017, and no releases.  You may want to just delete that out of your readme.

Is there a stable version of this that is python 3.4 compatible?

**Comment by freeseek** [comment]
Yes, I should update the README at some point. The script does not work anymore for Python 3.4 and the code should check for that. Any specific reason you cannot update Python? The project has been forked by Linekio in any case: https://github.com/Linekio/getmyancestors

**Comment by mk-j** [comment]
Yeah I'm on ubuntu 14.04 LTS which has python 3.4.  Its supported until 2019.  I think if you're writing this for yourself, you can use whatever python version you want.  But if you are writing it for other people, you may want it as compatible as possible, just a thought.  I still write in python2 for maximum compatibility.

**Comment by freeseek** [comment]
Unfortunately async is a required feature for the script. Without async the download of the family tree does not parallelize and the download of the family tree would go at least an order of magnitude slower. There are ways to upgrade python to version 3.5 or 3.6 for 14.04 LTS and I strongly advise you to look into that. As far as the broad choice of python for compatibility, python 2.7 will be retired in 2020 (https://pythonclock.org/) and at that point there will be no maintained version of Linux running python 3.4 or older. It is my opinion that older versions of python are maintained because there are many users/coders out there that do not want to make the effort to update. By giving them incentives to update, I believe overall I am doing a good thing. :-(
